version: '3.1'

services:
  nginx:
    networks:
      - app-tier
    build:
      context: ./
      dockerfile: dockerfile.nginx
    container_name: nginx-rtmp-web
    ports:
      - 8090:80
      - 1935:1935 
      - 8088:8088
      - 8091:8080
    volumes:
      - ../files/config/nginx/index.html:/usr/share/nginx/html/index.html
      - ../files/config/nginx/stat.xsl:/var/www/html/rtmp/stat.xsl
      - ../files/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../files/config/nginx/rtmp:/etc/nginx/sites-available/rtmp
  fpm:
      image: php:fpm
      container_name: fpm
      networks:
      - app-tier
      ports:
          - ":9000"
      volumes:
        - ../files/src/site/:/var/www/html/wordpress/
  auth-server:
    build:
      context: ./
      dockerfile: dockerfile.express
    container_name: auth-server
    networks:
      - app-tier
    ports:
      - "3000:3000"
    volumes:
      - ../files/src/express/:/usr/app/src

networks:
  app-tier:
    driver: bridge