version: '3.1'

services:
#database engine service
  nginx:
    networks:
      - app-tier
    build:
      context: ./
      dockerfile: dockerfile.nginx
    container_name: nginx-rtmp-web
#    environment:
#      key: "value"
    # depends_on:
    #   - redis
    ports:
      - 8090:80
      - 1935:1935 
      - 8088:8088
      - 8091:8080
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./files/stream_server/index.html:/usr/share/nginx/html/index.html
      - ./files/stream_server/stat.xsl:/var/www/html/rtmp/stat.xsl
      - ./files/stream_server/nginx.conf:/etc/nginx/nginx.conf

      - ./files/stream_server/rtmp:/etc/nginx/sites-available/rtmp
#      - ./files/stream_server/wordpress_pool.conf:/etc/php/8.2/fpm/pool.d/wordpress_pool.conf
#      - ./files/stream_server/php/index.php:/var/www/html/wordpress/index.php
  fpm:
      image: php:fpm
      networks:
      - app-tier
      ports:
          - ":9000"

      # seems like fpm receives the full path from nginx
      # and tries to find the files in this dock, so it must
      # be the same as nginx.root
      volumes:
        - ./files/php/site/:/var/www/html/wordpress/

networks:
  app-tier:
    driver: bridge