version: '3.1'

services:
#database engine service
  nginx:
    build:
      context: ./
      dockerfile: dockerfile.nginx
    container_name: nginx-rtmp-web
#    environment:
#      key: "value"
    # depends_on:
    #   - redis
    ports:
      - 8090:80
      - 1935:1935 
      - 8088:8088
      - 8091:8080
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./files/index.html:/usr/share/nginx/html/index.html
      - ./files/stat.xsl:/var/www/html/rtmp/stat.xsl
      - ./files/nginx.conf:/etc/nginx/nginx.conf
      - ./files/rtmp:/etc/nginx/sites-available/rtmp
      # - ./files/php:/var/www/html/rtmp