FROM nginx:latest

RUN apt update
RUN apt install -y nginx-common
RUN apt install -y libnginx-mod-rtmp
RUN apt install -y gzip
RUN service nginx-debug reload
RUN mkdir /var/www/html/rtmp
#RUN gzip -c /usr/share/doc/libnginx-mod-rtmp/examples/stat.xsl.gz > /var/www/html/rtmp/stat.xsl
RUN ln -s /etc/nginx/sites-available/rtmp /etc/nginx/sites-enabled/rtmp
RUN service nginx-debug reload
RUN mkdir /var/www/html/stream
RUN service nginx-debug reload

#COPY ./files/index.html /usr/share/nginx/html/index.html
